---
# This is a workflow meant for epitech students

name: Publish to DockerHub Epitech Project

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:
    # Only triggers for the master branch
    branches: [ master ]
    # Sequence of patterns matched against refs/tags

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish_dockerhub"
  publish_dockerhub:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: martinvanaud/r-type_server
          tag_with_ref: true
